### ISSUE TITLE
Apply all client information

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/crg-www#1]
Change all content and fields (logo, phone, email, name) to client info.

Biz card w/ logo applied: https://trello.com/c/eHlpxo43/7-biz-card

Client logo: 
![white](https://user-images.githubusercontent.com/5973579/29234107-af3e2c98-7ea9-11e7-813e-f7d6473eb7da.png)

![castle png](https://user-images.githubusercontent.com/5973579/29234108-af3e62c6-7ea9-11e7-87ea-226cd9e0d8b8.png)

**Comment by wingchunkf** [comment]
Logo looks great on local develop branch but alt text is appearing on remote branch. Will have to investigate this further.

**Comment by wingchunkf** [comment]
Issue resolved and logo is now visible.

**Comment by wingchunkf** [comment]
Logo has been changed to the correct color and tagline removed. This completes issue #1.
