### ISSUE TITLE
Business hours

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/crg-www#19]
At the top of the page there is a time frame indicating business hours. We want to add functionality to check the date/time from the clients machine and if it's inside business hours then show "We're Availalbe Now" or "We're Open" something classy/catchy.

> Make sure this looks good on both mobile and desktop views as well as not throwing off the flow of the line-height/heading area.

![screenshot 2017-08-15 07 34 27](https://user-images.githubusercontent.com/5973579/29320569-78188660-818c-11e7-8e4e-a7a7baaccd41.png)

**Comment by wingchunkf** [comment]
Wrote JS code to add messages based on whether business is open or closed. This fixes issue #19.
