### ISSUE TITLE
add Google Analytics custom events

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/crg-www#23]
GA is implemented on the site and @wingchunkf has been added to the GA dashboard as a user.

We need to implement custom Google Analytic events when a user clicks on different elements on the site.

We want to know when a user clicks on and element on the navbar as well as any of the buttons on the page that say "get a quote" or "free quote".

Resources:
https://www.youtube.com/watch?v=dERp9CYLAgg
https://developers.google.com/analytics/devguides/collection/gajs/eventTrackerGuide

**Comment by wingchunkf** [comment]
Code in events.js had to be altered for ga testing on local files. Will need to retest on develop branch before merging to master.
https://stackoverflow.com/questions/3591847/google-analytics-from-a-file-url
