### ISSUE TITLE
Setup an info@ email acct

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/crg-www#3]
We need an email account created for a general email inbox for the client info@castlerock-construction.com

This email can be forwarded to ray@castlerock-construction.com in the cpanel so a copy of each email will go to both inboxes.

- [x] create the email account in the cpanel

- [x] add info/password to Trello board

**Comment by wingchunkf** [comment]
Email account created, forwarding set up, and information recorded on Trello/Accounts, Info & Login/email accounts
