### ISSUE TITLE
business hours time logic

### ISSUE THREAD

**Issue by wingchunkf** [crobinson42/crg-www#31]
The UTC time in the main.js file needs to be adjusted so that the correct message (open/closed) displays.

**Comment by crobinson42** [comment]
Looking at the production env which is running off of `master` branch, the time is correct:
![screenshot 2017-08-18 13 38 15](https://user-images.githubusercontent.com/5973579/29476871-c2b1375e-841a-11e7-8c63-2800144e54d0.png)

Looking at PR #30 I think broke it.. currently in the DEV env which is running off of `develop` branch, the time is wrong. 
![screenshot 2017-08-18 13 40 27](https://user-images.githubusercontent.com/5973579/29476903-efc883dc-841a-11e7-9fad-5dd6dcd5cf02.png)

**Comment by crobinson42** [comment]
#32 PR moved the fix onto the dev branch
